export { default as home } from "./home.js";
export { default as login } from "./login.js";
export { default as register } from "./register.js";
export { default as search } from "./search.js";
export { default as profile } from "./profile.js";
export { default as notifications } from "./notifications.js";
export { default as othersProfile } from "./othersProfile.js";
export { default as pageNotFound } from "./pageNotFound.js";
export { default as thread } from "./thread.js";
